services:
  db:
    container_name: mssql_db
    image: mcr.microsoft.com/mssql/server:latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=dummy_password@1234
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
